name: CI/CD workflow for Billing

on:
  push:
    paths:
      - 'services/billing/**'
  pull_request:
    paths:
      - 'services/billing/**'



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Billing tests
        run: |
        cd services/billing
        npm install
        npm test

  deploy:
    if: github.refs == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        run: echo "Deploying Billing"
        
      
        
      
    
      
